name: yellow_app
description: The Yellow App
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_text_helpers:
    git:
      url: https://github.com/zvikarp/flutter_text_helpers
  flutter_svg: ^0.21.0-nullsafety.0
  dio: ^4.0.0-prev3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/icons/

  fonts:
    - family: CAPSLOCK
      fonts:
        - asset: assets/fonts/CAPSLOCK.ttf
          weight: 900
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato.ttf
          weight: 400
